### ISSUE TITLE
app threw an error during load

### ISSUE THREAD

**Issue by jezza3814** [tunip3/vantage-source-code#2]
App threw an error during load
TypeError: app.makeSingleInstance is not a function
    at Object.<anonymous> (C:\Users\jezza\Desktop\vantage-source-code-master\v2.1.2\index.js:73:28)
    at Object.<anonymous> (C:\Users\jezza\Desktop\vantage-source-code-master\v2.1.2\index.js:189:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at loadApplicationPackage (C:\Users\jezza\node_modules\electron\dist\resources\default_app.asar\main.js:119:12)
    at Object.<anonymous> (C:\Users\jezza\node_modules\electron\dist\resources\default_app.asar\main.js:164:5)
    at Object.<anonymous> (C:\Users\jezza\node_modules\electron\dist\resources\default_app.asar\main.js:204:3)

**Comment by tunip3** [comment]
did you run the command

electron index.js

do you have electron installed? if you are not sure you can check by running

electron -h

if you get a command not found error try to run 

npm install electron -g

please let me know if this fixed the issue

**Comment by jezza3814** [comment]
No it did not work it's still throwing the error

**Comment by jezza3814** [comment]
Sorry dude my bad, you need electron 2 you may want to state that
